version: '3'

services:

  shell:
    image: chembience/shell:${CHEMBIENCE_BUILD_LABEL}
    container_name: chembience_shell
    volumes:
      - "${CHEMBIENCE_HOME}:/home/chembience"
    networks:
      - sphere
    environment:
      - CHEMBIENCE_BUILD_LABEL
      - CHEMBIENCE_HOME
      - CHEMBIENCE_USER
      - CHEMBIENCE_UID
      - CHEMBIENCE_GID
    command: bash
    entrypoint: ""

networks:
  sphere:



