[uwsgi]
chmod-socket = 666
uid = root
gid = root
chdir = /home/app/appsite
master = true
threads = 2
socket = /tmp/app.sock
module = appsite.wsgi:application
logger = file:/tmp/app.log
vacuum = true

processes       = 10
max-requests    = 100

### uncomment this for development
#py-autoreload = 1
#touch-reload = /home/app/appsite

