#!/bin/bash
set -e

if [ $# -eq 0 ]; then
    echo "no targets provided (django|rdkit|jupyter|flask|all)"
    exit 1
fi

./env-prepare
source .env

CWD=$(pwd)
INIT_BASE=true

init_base() {
  if [ $INIT_BASE = false ]
  then
    return
  fi
  mkdir -p $CHEMBIENCE_SPHERE
  mkdir -p $CHEMBIENCE_SHARE
  docker-compose -f ./context/build/base/docker-compose.init.yml run --rm base
  cp .env $CHEMBIENCE_SPHERE
  cp .env $CHEMBIENCE_SHARE
  cd $CHEMBIENCE_SPHERE
  ./init
  docker network ls|grep chembience_sphere > /dev/null || docker network create --driver bridge chembience_sphere
  INIT_BASE=false
  cd $CWD
}

init_django() {
  init_base
  mkdir -p $DJANGO_APP_HOME
  docker-compose -f ./context/build/django/docker-compose.init.yml run --rm django
  cp .env $DJANGO_APP_HOME
  cd $DJANGO_APP_HOME
  ./init
  cd $CWD
}

init_rdkit() {
  init_base
  mkdir -p $RDKIT_APP_HOME
  docker-compose -f ./context/build/rdkit/docker-compose.init.yml run --rm rdkit
  cp .env $RDKIT_APP_HOME
  cd $RDKIT_APP_HOME
  ./init
  cd $CWD
}

init_jupyter () {
  init_base
  mkdir -p $JUPYTER_APP_HOME
  docker-compose -f ./context/build/jupyter/docker-compose.init.yml run --rm jupyter
  cp .env $JUPYTER_APP_HOME
  cd $JUPYTER_APP_HOME
  ./init
  cd $CWD
}

init_django=false
init_rdkit=false
init_jupyter=false
init_flask=false

while :; do
    case $1 in
        django) init_django=true
        ;;
        rdkit) init_rdkit=true
        ;;
        jupyter) init_jupyter=true
        ;;
        flask) init_flask=true
        ;;
        all) init_django=true;
             init_rdkit=true;
             init_jupyter=true;
             init_flask=true;
        ;;
        *) break
    esac
    shift
done

if [ $init_django = true ]
then
  echo "*** Initializing Chembience Django Template App ..."
  init_django
fi

if [ $init_rdkit = true ]
then
  echo "*** Initializing Chembience RDKit Template App ..."
  init_rdkit
fi

if [ $init_jupyter = true ]
then
  echo "*** Initializing Chembience Jupyter Template App ..."
  init_jupyter
fi

echo "-------------------------------------------------------------"
echo " Initialization has been finished (please read output above)"
echo "-------------------------------------------------------------"