#!/bin/bash

source .env

docker-compose -f $DJANGO_APP_HOME/docker-compose.yml down
docker-compose -f $RDKIT_APP_HOME/docker-compose.yml down
docker-compose -f $CHEMBIENCE_HOME/docker-compose.yml down


rm -rf $CHEMBIENCE_HOME && rm -rf $DJANGO_APP_HOME && rm -rf $RDKIT_APP_HOME
