version: '3'

services:

  rdkit:
    image: markussitzmann/chembience_rdkit:${CHEMBIENCE_BUILD_LABEL}
    container_name: chembience_rdkit
    volumes:
      - "${CHEMBIENCE_HOME}:/home/chembience"
      - "${RDKIT_APP_HOME}:/home/app"
    networks:
      - sphere
    environment:
      - CHEMBIENCE_HOME=${CHEMBIENCE_HOME}
      - CHEMBIENCE_USER=${CHEMBIENCE_USER}
      - CHEMBIENCE_UID=${CHEMBIENCE_UID}
      - CHEMBIENCE_GID=${CHEMBIENCE_GID}
      - CHEMBIENCE_DB_HOST=${CHEMBIENCE_DB_HOST}
      - CHEMBIENCE_DB_PORT=${CHEMBIENCE_DB_PORT}
      - CHEMBIENCE_DB_PASSWORD=${CHEMBIENCE_DB_PASSWORD}
      - APP_HOME=${RDKIT_APP_HOME}
    depends_on:
      - db
    command: ["python"]


  db:
    image: markussitzmann/chembience_db:${CHEMBIENCE_BUILD_LABEL}
    container_name: chembience_db
    volumes:
      - db_volume:/var/lib/postgresql
    networks:
      - sphere
    environment:
      - DEBUG=false
      - CHEMBIENCE_BUILD_LABEL
      - CHEMBIENCE_ROOT
      - CHEMBIENCE_HOME
      - CHEMBIENCE_USER
      - CHEMBIENCE_UID
      - CHEMBIENCE_GID
      - DB_USER=${CHEMBIENCE_USER}
      - DB_PASS=${CHEMBIENCE_DB_PASSWORD}
      - DB_NAME=${CHEMBIENCE_USER}
      - DB_TEMPLATE=
      - DB_EXTENSION=rdkit
      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=

volumes:
  db_volume:

networks:
  sphere:
