version: '3.9'

services:

  app:
    image: chembience/django-rdkit:${CHEMBIENCE_VERSION}
    container_name: ${APP_NAME}
    volumes:
      - ${APP_HOME}:/home/app
      - ${APP_HOME}/nginx:/home/nginx
      - ${CHEMBIENCE_SHARE}:/share
    ports:
       - ${APP_CONNECTION_PORT}:80
    networks:
      - app-network
      - chembience-network
    environment:
      - CHEMBIENCE_UID
      - CHEMBIENCE_GID
      - DJANGO_SUPERUSER_PASSWORD
      - DJANGO_SUPERUSER_USERNAME
      - DJANGO_SUPERUSER_EMAIL
      - POSTGRES_NAME
      - POSTGRES_USER
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_PASSWORD
      - APP_VIRTUAL_HOSTNAME=${APP_VIRTUAL_HOSTNAME}
      - VIRTUAL_HOST=${APP_VIRTUAL_HOSTNAME}
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
      - LETSENCRYPT_TEST
    depends_on:
      - postgres
    entrypoint: ["/home/app/docker-entrypoint.sh"]
    command: ["/home/nginx/run.sh"]

  postgres:
    image: chembience/postgres-rdkit:${POSTGRES_RDKIT_VERSION}
    container_name: ${APP_NAME}-postgres
    volumes:
      - postgres-db-volume:/var/lib/postgresql
      - ${APP_HOME}/postgres-init.d:/docker-entrypoint-initdb.d
    networks:
      - app-network
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    #restart: always

volumes:
  postgres-db-volume:

networks:
  app-network:
    name: ${APP_NAME}-backend
  chembience-network:
    name: chembience-network

