#!/bin/bash

cp app.env .env
source .env

if [ -z $(docker network ls --filter name=^${APP_NAME}_backend$ --format="{{ .Name }}") ] ; then
     echo "creating Docker network"
     docker network create ${APP_NAME}_backend ;
else
    echo "App Docker network exists"
fi

if [ -z $(docker network ls --filter name=^chembience_network$ --format="{{ .Name }}") ] ; then
     echo "Creating chembience network"
     docker network create chembience_network ;
fi

echo "done"

exit 0
