version: '3'

services:

  proxy:
    image: chembience/proxy:${CHEMBIENCE_BUILD_LABEL}
    container_name: chembience_proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "${CHEMBIENCE_SPHERE}:/home/sphere"
    ports:
      - "80:80"
    networks:
      - sphere

  shell:
    image: chembience/shell:${CHEMBIENCE_BUILD_LABEL}
    container_name: chembience_shell
    command: bash
    volumes:
      - "${CHEMBIENCE_SPHERE}:/home/spheres"
    networks:
      - sphere
    environment:
      - CHEMBIENCE_BUILD_LABEL
      #- CHEMBIENCE_HOME
      #- CHEMBIENCE_USER
      - CHEMBIENCE_UID
      - CHEMBIENCE_GID

  db:
    image: chembience/db:${CHEMBIENCE_BUILD_LABEL}
    container_name: chembience_db
    volumes:
      - db_volume:/var/lib/postgresql
    networks:
      - sphere
    environment:
      - DEBUG=false
      - CHEMBIENCE_BUILD_LABEL
      - CHEMBIENCE_ROOT
      - CHEMBIENCE_HOME
      - CHEMBIENCE_USER
      - CHEMBIENCE_UID
      - CHEMBIENCE_GID
      - DB_USER=${CHEMBIENCE_DB_USER}
      - DB_PASS=${CHEMBIENCE_DB_PASSWORD}
      - DB_NAME=${CHEMBIENCE_USER}
      - DB_TEMPLATE=
      - DB_EXTENSION=rdkit
      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=

volumes:
  db_volume:

networks:
  sphere:



