version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201711-01
    working_directory: ~/chembience
    steps:
      - checkout
      - run: |
          cd ./context/base
          docker-compose -f docker-compose.build.yml pull
          docker-compose -f docker-compose.build.yml build