version: 2

jobs:
  prepare:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Prepare
          working_directory: .
          command: |
            rm -rf ~/chembient
            docker system prune -f --volumes
            ./docker/rm-all-images || true
            ./env-prepare
            docker login -u $DOCKER_USER -p $DOCKER_PASS
  base:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Build base
          working_directory: .
          command: |
            ./env-prepare
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f ./context/build/docker-compose.build.yml build base
            docker-compose -f ./context/build/docker-compose.build.yml push base
  python-base:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Build Python base
          working_directory: .
          command: |
            ./env-prepare
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f ./context/build/docker-compose.build.yml build python-base
            docker-compose -f ./context/build/docker-compose.build.yml push python-base
  rdkit-base:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Build RDKit base
          working_directory: .
          command: |
            ./env-prepare
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f ./context/build/docker-compose.build.yml build rdkit-base
            docker-compose -f ./context/build/docker-compose.build.yml push rdkit-base
  django-base:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Build Django base
          working_directory: .
          command: |
            ./env-prepare
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f ./context/build/docker-compose.build.yml build django-base
            docker-compose -f ./context/build/docker-compose.build.yml push django-base
  jupyter-base:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Build Jupyter base
          working_directory: .
          command: |
            ./env-prepare
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f ./context/build/docker-compose.build.yml build jupyter-base
            docker-compose -f ./context/build/docker-compose.build.yml push jupyter-base
  proxy:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Build proxy
          working_directory: .
          command: |
            ./env-prepare
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f ./context/app/docker-compose.build.yml build proxy
            docker-compose -f ./context/app/docker-compose.build.yml push proxy
  shell:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Build shell
          working_directory: .
          command: |
            ./env-prepare
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f ./context/app/docker-compose.build.yml build shell
            docker-compose -f ./context/app/docker-compose.build.yml push shell
  django:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Build django
          working_directory: .
          command: |
            ./env-prepare
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f ./context/app/docker-compose.build.yml build django
            docker-compose -f ./context/app/docker-compose.build.yml push django
  django-test:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Django test
          working_directory: .
          command: |
            ./app-prepare && cd ~/chembient/django && ./init && sleep 120 && ./django-manage-py migrate
            ./django-manage-py createsuperuser --username test --noinput --email test@test.org
            ./django-manage-py collectstatic
            ./down
  jupyter:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Build jupyter
          working_directory: .
          command: |
            ./env-prepare
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f ./context/app/docker-compose.build.yml build jupyter
            docker-compose -f ./context/app/docker-compose.build.yml push jupyter
  jupyter-test:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Jupyter test
          working_directory: .
          command: |
            ./app-prepare && sleep 60 && cd ~/chembient/jupyter && ./init && sleep 120 && docker-compose run app bash -ci "gosu app bash -c 'jupyter --version'" && ./down
  rdkit:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Build RDKit
          working_directory: .
          command: |
            ./env-prepare
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f ./context/app/docker-compose.build.yml build rdkit
            docker-compose -f ./context/app/docker-compose.build.yml push rdkit
  rdkit-test:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: false
    steps:
      - checkout
      - run: 
          name: Test RDKit
          working_directory: .
          command: |
            ./app-prepare && sleep 120 && cd ~/chembient/rdkit && ./init && ./run script.py && sleep 60

workflows:
  version: 2
  chembience-compile-build:
    jobs:
      - prepare:
          filters:
            branches:
              only: deploy
      - proxy:
          requires:
           - prepare
          filters:
            branches:
              only: deploy
      - base:
          requires:
            - prepare
          filters:
            branches:
              only: deploy
      - python-base:
          requires:
            - prepare
            - base
          filters:
            branches:
              only: deploy
      - rdkit-base:
          requires:
            - prepare
            - python-base
          filters:
            branches:
              only: deploy
      - django-base:
          requires:
            - prepare
            - rdkit-base
          filters:
            branches:
              only: deploy
      - jupyter-base:
          requires:
            - prepare
            - rdkit-base
          filters:
            branches:
              only: deploy
      - shell:
          requires:
            - prepare
            - base
          filters:
            branches:
              only: deploy
      - django:
          requires:
            - django-base
          filters:
            branches:
              only: deploy
      - jupyter:
          requires:
            - jupyter-base
          filters:
            branches:
              only: deploy
      - rdkit:
          requires:
            - rdkit-base
          filters:
            branches:
              only: deploy
      - rdkit-test:
          requires:
            - prepare
            - rdkit
          filters:
            branches:
              only: deploy
      - django-test:
          requires:
            - prepare
            - rdkit-test
            - django
            - proxy
          filters:
            branches:
              only: deploy
      - jupyter-test:
          requires:
            - prepare
            - django-test
            - jupyter
            - proxy
          filters:
            branches:
              only: deploy

