version: 2

jobs:
  chembience-build:
    machine:
      image: circleci/classic:201711-01
    working_directory: ~/chembience
    steps:
      - checkout
      - run:
          name: Build Base
          command: |
            cd ./context/base
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f docker-compose.build.yml pull --ignore-pull-failures base
            docker-compose -f docker-compose.build.yml build base
            docker-compose -f docker-compose.build.yml push base


workflows:
  version: 2
  chembience-workflow:
    jobs:
      - chembience-build
