version: 2

jobs:
  build-rdkit-conda-compile:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Compile Conda RDKit
          working_directory: ./context/base
          command: |
            cp ../../.env .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f docker-compose.build.yml pull --ignore-pull-failures rdkit-conda-compile
            docker-compose -f docker-compose.build.yml build rdkit-conda-compile
            docker-compose -f docker-compose.build.yml push rdkit-conda-compile
  build-rdkit-postgres-compile:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Compile Postgres RDKit
          working_directory: ./context/base
          command: |
             cp ../../.env .
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             docker-compose -f docker-compose.build.yml pull --ignore-pull-failures rdkit-postgres-compile
             docker-compose -f docker-compose.build.yml build rdkit-postgres-compile
             docker-compose -f docker-compose.build.yml push rdkit-postgres-compile
  build-base:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build base
          working_directory: ./context/base
          command: |
            cp ../../.env .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f docker-compose.build.yml pull --ignore-pull-failures base
            docker-compose -f docker-compose.build.yml build base
            docker-compose -f docker-compose.build.yml push base
  build-python-base:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build Python base
          working_directory: ./context/base
          command: |
            cp ../../.env .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f docker-compose.build.yml pull --ignore-pull-failures python_base
            docker-compose -f docker-compose.build.yml build python_base
            docker-compose -f docker-compose.build.yml push python_base
  build-rdkit-base:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build RDKit base
          working_directory: ./context/base
          command: |
            cp ../../.env .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f docker-compose.build.yml pull --ignore-pull-failures rdkit_base
            docker-compose -f docker-compose.build.yml build rdkit_base
            docker-compose -f docker-compose.build.yml push rdkit_base
  build-django-base:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build Django base
          working_directory: ./context/base
          command: |
            cp ../../.env .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f docker-compose.build.yml pull --ignore-pull-failures django_base
            docker-compose -f docker-compose.build.yml build django_base
            docker-compose -f docker-compose.build.yml push django_base
  build-jupyter-base:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build Jupyter base
          working_directory: ./context/base
          command: |
            cp ../../.env .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f docker-compose.build.yml pull --ignore-pull-failures jupyter_base
            docker-compose -f docker-compose.build.yml build jupyter_base
            docker-compose -f docker-compose.build.yml push jupyter_base
  build-proxy:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build Apps
          working_directory: ./context/app
          command: |
            cp ../../.env .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f docker-compose.build.yml pull --ignore-pull-failures proxy
            docker-compose -f docker-compose.build.yml build proxy
            docker-compose -f docker-compose.build.yml push proxy
  build-shell:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build shell
          working_directory: ./context/app
          command: |
            cp ../../.env .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f docker-compose.build.yml pull --ignore-pull-failures shell
            docker-compose -f docker-compose.build.yml build shell
            docker-compose -f docker-compose.build.yml push shell
  build-db:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build db
          working_directory: ./context/app
          command: |
            cp ../../.env .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f docker-compose.build.yml pull --ignore-pull-failures db
            docker-compose -f docker-compose.build.yml build db
            docker-compose -f docker-compose.build.yml push db
  build-django:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build django
          working_directory: ./context/app
          command: |
            cp ../../.env .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f docker-compose.build.yml pull --ignore-pull-failures django
            docker-compose -f docker-compose.build.yml build django
            docker-compose -f docker-compose.build.yml push django
  build-jupyter:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build jupyter
          working_directory: ./context/app
          command: |
            cp ../../.env .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f docker-compose.build.yml pull --ignore-pull-failures jupyter
            docker-compose -f docker-compose.build.yml build jupyter
            docker-compose -f docker-compose.build.yml push jupyter
  build-rdkit:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build RDKit
          working_directory: ./context/app
          command: |
            cp ../../.env .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f docker-compose.build.yml pull --ignore-pull-failures rdkit
            docker-compose -f docker-compose.build.yml build rdkit
            docker-compose -f docker-compose.build.yml push rdkit

workflows:
  version: 2
  chembience-workflow:
    jobs:
      - build-rdkit-conda-compile
      - build-rdkit-postgres-compile
      - build-proxy
      - build-base
      - build-python-base:
          requires:
            - build-base
      - build-rdkit-base:
          requires:
            - build-rdkit-conda-compile
            - build-python-base
      - build-django-base:
          requires:
            - build-rdkit-base
      - build-jupyter-base:
          requires:
            - build-rdkit-base
      - build-db:
          requires:
            - build-base
            - build-rdkit-postgres-compile
      - build-shell:
          requires:
            - build-base
      - build-django:
          requires:
            - build-django-base
      - build-jupyter:
          requires:
            - build-jupyter-base
      - build-rdkit:
          requires:
            - build-rdkit-base
