version: 2

jobs:
  prepare:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Prepare
          working_directory: .
          command: |
            rm -rf ~/chembient
            docker system prune -f --volumes
            ./docker/rm-all-images || true
            ./env-prepare
            docker login -u $DOCKER_USER -p $DOCKER_PASS
  rdkit-postgres-compile:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Compile Postgres RDKit
          working_directory: .
          command: |
             ./env-prepare
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             docker-compose -f ./context/build/docker-compose.build.yml pull --ignore-pull-failures rdkit-postgres-compile
             docker-compose -f ./context/build/docker-compose.build.yml build rdkit-postgres-compile
             docker-compose -f ./context/build/docker-compose.build.yml push rdkit-postgres-compile
#  rdkit-compile:
#    machine:
#      image: circleci/classic:201711-01
#      docker_layer_caching: false
#    steps:
#      - checkout
#      - run:
#          name: Compile RDKit
#          working_directory: .
#          command: |
#            ./env-prepare
#            docker login -u $DOCKER_USER -p $DOCKER_PASS
#            docker-compose -f ./context/build/docker-compose.build.yml pull --ignore-pull-failures rdkit-compile
#            docker-compose -f ./context/build/docker-compose.build.yml build rdkit-compile
#            docker-compose -f ./context/build/docker-compose.build.yml push rdkit-compile
  base:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Build base
          working_directory: .
          command: |
            ./env-prepare
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f ./context/build/docker-compose.build.yml pull --ignore-pull-failures base
            docker-compose -f ./context/build/docker-compose.build.yml build base
            docker-compose -f ./context/build/docker-compose.build.yml push base
  python-base:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Build Python base
          working_directory: .
          command: |
            ./env-prepare
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f ./context/build/docker-compose.build.yml pull --ignore-pull-failures python-base
            docker-compose -f ./context/build/docker-compose.build.yml build python-base
            docker-compose -f ./context/build/docker-compose.build.yml push python-base
  rdkit-base:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Build RDKit base
          working_directory: .
          command: |
            ./env-prepare
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f ./context/build/docker-compose.build.yml pull --ignore-pull-failures rdkit-base
            docker-compose -f ./context/build/docker-compose.build.yml build rdkit-base
            docker-compose -f ./context/build/docker-compose.build.yml push rdkit-base
  django-base:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Build Django base
          working_directory: .
          command: |
            ./env-prepare
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f ./context/build/docker-compose.build.yml pull --ignore-pull-failures django-base
            docker-compose -f ./context/build/docker-compose.build.yml build django-base
            docker-compose -f ./context/build/docker-compose.build.yml push django-base
  jupyter-base:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Build Jupyter base
          working_directory: .
          command: |
            ./env-prepare
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f ./context/build/docker-compose.build.yml pull --ignore-pull-failures jupyter-base
            docker-compose -f ./context/build/docker-compose.build.yml build jupyter-base
            docker-compose -f ./context/build/docker-compose.build.yml push jupyter-base
  proxy:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Build proxy
          working_directory: .
          command: |
            ./env-prepare
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f ./context/app/docker-compose.build.yml pull --ignore-pull-failures proxy
            docker-compose -f ./context/app/docker-compose.build.yml build proxy
            docker-compose -f ./context/app/docker-compose.build.yml push proxy
  shell:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Build shell
          working_directory: .
          command: |
            ./env-prepare
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f ./context/app/docker-compose.build.yml pull --ignore-pull-failures shell
            docker-compose -f ./context/app/docker-compose.build.yml build shell
            docker-compose -f ./context/app/docker-compose.build.yml push shell
  db:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Build db
          working_directory: .
          command: |
            ./env-prepare
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f ./context/app/docker-compose.build.yml pull --ignore-pull-failures db
            docker-compose -f ./context/app/docker-compose.build.yml build db
            docker-compose -f ./context/app/docker-compose.build.yml push db
  django:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Build django
          working_directory: .
          command: |
            ./env-prepare
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f ./context/app/docker-compose.build.yml pull --ignore-pull-failures django
            docker-compose -f ./context/app/docker-compose.build.yml build django
            docker-compose -f ./context/app/docker-compose.build.yml push django
  django-test:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Django test
          working_directory: .
          command: |
            ./init && cd ~/chembient/django && ./up && sleep 120 && ./django-manage-py migrate
            ./django-manage-py createsuperuser --username test --noinput --email test@test.org
            ./django-manage-py collectstatic
            ./down
  jupyter:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Build jupyter
          working_directory: .
          command: |
            ./env-prepare
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f ./context/app/docker-compose.build.yml pull --ignore-pull-failures jupyter
            docker-compose -f ./context/app/docker-compose.build.yml build jupyter
            docker-compose -f ./context/app/docker-compose.build.yml push jupyter
  jupyter-test:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Jupyter test
          working_directory: .
          command: |
            ./init && sleep 60 && cd ~/chembient/jupyter && ./up && sleep 120 && ./jupyter --version && ./down
  rdkit:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: Build RDKit
          working_directory: .
          command: |
            ./env-prepare
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f ./context/app/docker-compose.build.yml pull --ignore-pull-failures rdkit
            docker-compose -f ./context/app/docker-compose.build.yml build rdkit
            docker-compose -f ./context/app/docker-compose.build.yml push rdkit
  rdkit-test:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: false
    steps:
      - checkout
      - run: 
          name: Test RDKit
          working_directory: .
          command: |
            ./init && sleep 120 && cd ~/chembient/rdkit && ./run script.py && sleep 60

workflows:
  version: 2
  chembience-compile-build:
    jobs:
      - prepare:
          filters:
            branches:
              only:
                - deploy
                - develop
      - rdkit-postgres-compile:
          requires:
            - prepare
          filters:
            branches:
              only:
                - deploy
                - develop
#      - rdkit-compile:
#          requires:
#            - prepare
#          filters:
#            branches:
#              only: deploy
      - proxy:
          requires:
           - prepare
          filters:
            branches:
              only:
                - deploy
                - develop
      - base:
          requires:
            - prepare
          filters:
            branches:
              only:
               - deploy
               - develop
      - python-base:
          requires:
            - prepare
            - base
          filters:
            branches:
              only:
                - deploy
                - develop
      - rdkit-base:
          requires:
            - prepare
            - python-base
          filters:
            branches:
              only:
                - deploy
                - develop
      - django-base:
          requires:
            - prepare
            - rdkit-base
          filters:
            branches:
              only:
                - deploy
                - develop
      - jupyter-base:
          requires:
            - prepare
            - rdkit-base
          filters:
            branches:
              only:
              - deploy
              - develop
      - db:
          requires:
            - prepare
            - base
            - rdkit-postgres-compile
          filters:
            branches:
              only:
               - deploy
               - develop
      - shell:
          requires:
            - prepare
            - base
          filters:
            branches:
              only:
                - deploy
                - develop
      - django:
          requires:
            - django-base
          filters:
            branches:
              only:
                - deploy
                - develop
      - jupyter:
          requires:
            - jupyter-base
          filters:
            branches:
              only:
                - deploy
                - develop
      - rdkit:
          requires:
            - rdkit-base
          filters:
            branches:
              only:
                - deploy
                - develop
      - rdkit-test:
          requires:
            - prepare
            - rdkit
            - db
          filters:
            branches:
              only:
                - deploy
                - develop
      - django-test:
          requires:
            - prepare
            - rdkit-test
            - django
            - db
            - proxy
          filters:
            branches:
              only:
                - deploy
                - develop
      - jupyter-test:
          requires:
            - prepare
            - django-test
            - jupyter
            - db
            - proxy
          filters:
            branches:
              only:
                - deploy
                - develop

