version: 2

jobs:
  prepare:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Prepare
          working_directory: .
          command: |
            rm -rf ~/chembient
            docker system prune -f --volumes
            cp .env ./context/base
            cp .env ./context/app
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f ./context/base/docker-compose.build.yml pull --ignore-pull-failures
            docker-compose -f ./context/app/docker-compose.build.yml pull --ignore-pull-failures
  rdkit-conda-compile:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Compile Conda RDKit
          working_directory: .
          command: |
            docker-compose -f ./context/base/docker-compose.build.yml build rdkit-conda-compile
  rdkit-postgres-compile:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Compile Postgres RDKit
          working_directory: .
          command: |
             docker-compose -f ./context/base/docker-compose.build.yml build rdkit-postgres-compile
  base:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build base
          working_directory: .
          command: |
            docker-compose -f ./context/base/docker-compose.build.yml build base
  python-base:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build Python base
          working_directory: .
          command: |
            docker-compose -f ./context/base/docker-compose.build.yml build python_base
  rdkit-base:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build RDKit base
          working_directory: .
          command: |
            docker-compose -f ./context/base/docker-compose.build.yml build rdkit_base
  django-base:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build Django base
          working_directory: .
          command: |
            docker-compose -f ./context/base/docker-compose.build.yml build django_base
  jupyter-base:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build Jupyter base
          working_directory: .
          command: |
            docker-compose -f ./context/base/docker-compose.build.yml build jupyter_base
  proxy:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build proxy
          working_directory: .
          command: |
            docker-compose -f ./context/app/docker-compose.build.yml build proxy
  shell:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build shell
          working_directory: .
          command: |
            docker-compose -f ./context/app/docker-compose.build.yml build shell
  db:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build db
          working_directory: .
          command: |
            docker-compose -f ./context/app/docker-compose.build.yml build db
  django:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build django
          working_directory: .
          command: |
            docker-compose -f ./context/app/docker-compose.build.yml build django
  django-test:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Django test
          working_directory: .
          command: |
            ./init && cd ~/chembient/django && ./up && sleep 30
            ./django-manage-py migrate
            ./django-manage-py createsuperuser --username test --noinput --email test@test.org
            ./django-manage-py collectstatic
            status_code=$(curl -o /dev/null --silent --head --write-out '%{http_code}\n' http://django.localhost)
            if [ $status_code -ne "200" ]
            then
                echo "http status check failed"
                ./down
                exit 1
            fi
            ./down
  jupyter:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build jupyter
          working_directory: .
          command: |
            docker-compose -f ./context/app/docker-compose.build.yml build jupyter
  jupyter-test:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Jupyter test
          working_directory: .
          command: |
            ./init && cd ~/chembient/jupyter && ./up && sleep 30 &&
            ./jupyter --version
            status_code=$(curl -o /dev/null --silent --head --write-out '%{http_code}\n' http://jupyter.localhost)
            if [ $status_code -ne "200" ]
            then
                echo "http status check failed"
                ./down
                exit 1
            fi
            ./down
  rdkit:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build RDKit
          working_directory: .
          command: |
            docker-compose -f ./context/app/docker-compose.build.yml build rdkit
  rdkit-test:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run: ./init
      - run: sleep 30 && cd ~/chembient/rdkit && ./run script.py
  deploy:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Prepare
          working_directory: .
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f ./context/base/docker-compose.build.yml push
            docker-compose -f ./context/app/docker-compose.build.yml push

workflows:
  version: 2
  chembience-compile-build:
    jobs:
      - prepare
      - rdkit-conda-compile:
          requires:
            - prepare
          filters:
            branches:
              only:
                - compile
      - rdkit-postgres-compile:
          requires:
            - prepare
          filters:
            branches:
              only:
                - compile
      - proxy:
          requires:
            - prepare
      - base:
          requires:
            - prepare
      - python-base:
          requires:
            - prepare
            - base
      - rdkit-base:
          requires:
            - prepare
            - rdkit-conda-compile
            - python-base
      - django-base:
          requires:
            - prepare
            - rdkit-base
      - jupyter-base:
          requires:
            - prepare
            - rdkit-base
      - db:
          requires:
            - prepare
            - base
            - rdkit-postgres-compile
      - shell:
          requires:
            - prepare
            - base
      - django:
          requires:
            - django-base
      - jupyter:
          requires:
            - jupyter-base
      - rdkit:
          requires:
            - rdkit-base
      - rdkit-test:
          requires:
            - rdkit
            - db
      - django-test:
          requires:
            - rdkit-test
            - django
            - db
            - proxy
      - juypter-test:
          requires:
            - django-test
            - jupyter
            - db
            - proxy
      - deploy:
          requires:
            - rdkit-test
            - django-test
            - juypter-test
