version: 2

jobs:
  build:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build base
          working_directory: ./context/base
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f docker-compose.build.yml pull --ignore-pull-failures base
            docker-compose -f docker-compose.build.yml build base
            docker-compose -f docker-compose.build.yml push base
      - run:
          name: Build python_base
          working_directory: ./context/base
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f docker-compose.build.yml pull --ignore-pull-failures python_base
            docker-compose -f docker-compose.build.yml build python_base
            docker-compose -f docker-compose.build.yml push python_base
      - run:
          name: Build rdkit_base
          working_directory: ./context/base
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker-compose -f docker-compose.build.yml pull --ignore-pull-failures rdkit_base
            docker-compose -f docker-compose.build.yml build rdkit_base
            docker-compose -f docker-compose.build.yml push rdkit_base


workflows:
  version: 2
  chembience-workflow:
    jobs:
      - build
