version: '3.9'

services:

  app:
    image: chembience/rdkit:${APP_VERSION}
    container_name: ${APP_NAME}
    volumes:
      - ${APP_HOME}:/home/app
      - ${CHEMBIENCE_SPHERE}:/home/sphere
      - ${CHEMBIENCE_SHARE}:/share
    networks:
      - sphere
    environment:
      - CHEMBIENCE_UID
      - CHEMBIENCE_GID
      - CHEMBIENCE_POSTGRES_USER
      - CHEMBIENCE_POSTGRES_HOST
      - CHEMBIENCE_POSTGRES_PORT
      - CHEMBIENCE_POSTGRES_PASSWORD
    depends_on:
      - postgres
    entrypoint: ["/home/app/docker-entrypoint.sh"]
    command: ["python"]


  postgres:
    image: chembience/postgres-rdkit:${CHEMBIENCE_POSTGRES_RDKIT_VERSION}
    container_name: ${APP_NAME}_postgres
    volumes:
      - postgres_db_volume:/var/lib/postgresql
      - ${APP_HOME}/postgres-init.d:/docker-entrypoint-initdb.d
    #restart: always
    networks:
      - sphere
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER

volumes:
  postgres_db_volume:

networks:
  app_network:
    external:
      name: ${APP_NAME}_backend
  sphere:
    external:
      name: chembience_sphere

