version: '3.9'

services:

  app:
    image: ${APP_NAME}:${APP_VERSION}
    container_name: ${APP_CONTAINER_NAME}
    volumes:
      - ${APP_HOME}:/home/app
      - ${CHEMBIENCE_SHARE}:/share
    networks:
      - app-network
    environment:
      - CHEMBIENCE_UID
      - CHEMBIENCE_GID
      - POSTGRES_USER
      - POSTGRES_NAME
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_PASSWORD
    depends_on:
      - postgres
    working_dir: "/home/app"
    entrypoint: ["/home/app/docker-entrypoint.sh"]
    command: ["python"]

  postgres:
    image: chembience/postgres-rdkit:${POSTGRES_RDKIT_VERSION}
    container_name: ${APP_NAME}-postgres-container
    volumes:
      - postgres-db-volume:/var/lib/postgresql
      - ${APP_HOME}/postgres-init.d:/docker-entrypoint-initdb.d
    #restart: always
    networks:
      - app-network
    environment:
      - POSTGRES_USER
      - POSTGRES_NAME
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_PASSWORD

volumes:
  postgres-db-volume:

networks:
  app-network:
    name: ${APP_NAME}-backend


