#!/bin/bash

cp app.env .env
source .env

NETWORK_NAME=${APP_NAME}_backend
if [ -z $(docker network ls --filter name=^${NETWORK_NAME}$ --format="{{ .Name }}") ] ; then
     echo "Creating app backend network $NETWORK_NAME"
     docker network create ${NETWORK_NAME} ;
fi
if [ -z $(docker network ls --filter name=^chembience_network$ --format="{{ .Name }}") ] ; then
     echo "Creating chembience network"
     docker network create chembience_network ;
fi

echo "Done."

exit 0
