#!/bin/bash

echo "Running $@"

docker-compose exec app bash -ci "gosu chembience bash -c 'cd /home/app/appsite && ./manage.py $*'"


#docker-compose run --rm app bash -ci "\
#	cd /home/apps/ &&\
#	./manage.py $*"