version: '3'

services:

  djangoapp:
    image: markussitzmann/chembience_djangoapp:${CHEMBIENCE_BUILD_LABEL}
    container_name: chembience_djangoapp
    volumes:
      - "${CHEMBIENCE_HOME}:/home/chembience"
      - "${DJANGO_APP_HOME}:/home/app"
    ports:
       - "${DJANGO_APP_CONNECTION_PORT}:80"
    networks:
      - sphere
    environment:
      - CHEMBIENCE_HOME=${CHEMBIENCE_HOME}
      - CHEMBIENCE_USER=${CHEMBIENCE_USER}
      - CHEMBIENCE_UID=${CHEMBIENCE_UID}
      - CHEMBIENCE_GID=${CHEMBIENCE_GID}
      - CHEMBIENCE_DB_HOST=${CHEMBIENCE_DB_HOST}
      - CHEMBIENCE_DB_PORT=${CHEMBIENCE_DB_PORT}
      - CHEMBIENCE_DB_PASSWORD=${CHEMBIENCE_DB_PASSWORD}
      - DJANGO_APP_HOME=${DJANGO_APP_HOME}
      - DJANGO_APP_VIRTUAL_HOSTNAME=${DJANGO_APP_VIRTUAL_HOSTNAME}
      - VIRTUAL_HOST=${DJANGO_APP_VIRTUAL_HOSTNAME}
    depends_on:
      - proxy
      - db

  proxy:
    image: markussitzmann/chembience_proxy:${CHEMBIENCE_BUILD_LABEL}
    container_name: chembience_proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "${CHEMBIENCE_HOME}:/home/chembience"
    ports:
      - "${PROXY_EXTERNAL_PORT}:80"
    networks:
      - sphere

  db:
    image: markussitzmann/chembience_db:${CHEMBIENCE_BUILD_LABEL}
    container_name: chembience_db
    volumes:
      - db_volume:/var/lib/postgresql
    networks:
      - sphere
    environment:
      - DEBUG=false
      - CHEMBIENCE_BUILD_LABEL
      - CHEMBIENCE_ROOT
      - CHEMBIENCE_HOME
      - CHEMBIENCE_USER
      - CHEMBIENCE_UID
      - CHEMBIENCE_GID
      - DB_USER=${CHEMBIENCE_USER}
      - DB_PASS=${CHEMBIENCE_DB_PASSWORD}
      - DB_NAME=${CHEMBIENCE_USER}
      - DB_TEMPLATE=
      - DB_EXTENSION=rdkit
      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=

volumes:
  db_volume:

networks:
  sphere:
