
x-common-environment: &common-env
  CHEMBIENCE_UID: ${CHEMBIENCE_UID:-1000}
  CHEMBIENCE_GID: ${CHEMBIENCE_GID:-1000}
  DJANGO_VIRTUAL_HOSTNAME: ${APP_VIRTUAL_HOSTNAME:-localhost}
  DJANGO_SUPERUSER_PASSWORD: Django0Django0
  DJANGO_SUPERUSER_USERNAME: admin
  DJANGO_SUPERUSER_EMAIL: admin@domain.com
  POSTGRES_USER: chembience
  POSTGRES_PASSWORD: Chembience0
  POSTGRES_NAME: ${POSTGRES_NAME:-chembience}
  POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
  POSTGRES_PORT: ${POSTGRES_PORT:-5432}

services:

  rdkit:
    image: chembience/rdkit:${CHEMBIENCE_VERSION}
    build:
      context: rdkit/
      args:
        conda_package: 'continuumio/miniconda3'
        conda_tag: '24.11.1-0'
        conda_py: '312'
        rdkit_version: 'Release_2024_09_5'
    environment:
      <<: *common-env
    working_dir: "/home/app"
    networks:
      - app-network
    entrypoint: [ "/docker-entrypoint.sh" ]
    command: [ "python" ]

  django:
    image: chembience/rdkit-django:${CHEMBIENCE_VERSION}
    build:
      context: django/
      args:
        build_tag: ${CHEMBIENCE_VERSION}
    environment:
      <<: *common-env
    ports:
      - "8000:8000"
      #- "8000:8000"
    volumes:
      - ~/app:/home/app
    networks:
      - app-network
    working_dir: "/home/app/"
    entrypoint: [ "/docker-entrypoint.sh" ]
    command: ["gunicorn", "appsite.wsgi:application", "--bind", "0.0.0.0:8000"]

  postgres:
    image: chembience/rdkit-postgres:${CHEMBIENCE_VERSION}
    build:
      context: postgres/
      args:
        build_tag: ${CHEMBIENCE_VERSION}
    volumes:
      - postgres-db-volume:/home/postgres
      #- ${APP_HOME}/postgres-init.d:/docker-entrypoint-initdb.d
    environment:
      <<: *common-env
    ports:
      - "5432:5432"
    networks:
      - app-network
    working_dir: "/home/postgres/"
    entrypoint: [ "/docker-entrypoint.sh" ]

volumes:
  postgres-db-volume:

networks:
  app-network:
    name: app-backend
  chembience-network:
    name: chembience-network