version: '3'

services:

  base:
    image: markussitzmann/chembience_base:${CHEMBIENCE_BUILD_LABEL}
    build:
      context: base/
    volumes:
      - "${CHEMBIENCE_HOME}:/home/chembience"
    environment:
      - CHEMBIENCE_BUILD_LABEL
      - CHEMBIENCE_HOME
      - CHEMBIENCE_USER
      - CHEMBIENCE_UID
      - CHEMBIENCE_GID

  proxy:
    image: markussitzmann/chembience_proxy:${CHEMBIENCE_BUILD_LABEL}
    build:
      context: https://github.com/markussitzmann/nginx-proxy.git#chembience

  python:
    image: markussitzmann/chembience_python:${CHEMBIENCE_BUILD_LABEL}
    build:
      context: python/
      args:
        build_label: ${CHEMBIENCE_BUILD_LABEL}
    depends_on:
      - base

  rdkit:
    image: markussitzmann/chembience_rdkit:${CHEMBIENCE_BUILD_LABEL}
    build:
      context: rdkit/
      args:
        build_label: ${CHEMBIENCE_BUILD_LABEL}
    depends_on:
      - python

  django:
    image: markussitzmann/chembience_django:${CHEMBIENCE_BUILD_LABEL}
    build:
      context: django/
      args:
        build_label: ${CHEMBIENCE_BUILD_LABEL}
    depends_on:
      - rdkit

  shell:
    image: markussitzmann/chembience_shell:${CHEMBIENCE_BUILD_LABEL}
    build:
      context: shell/
      args:
        build_label: ${CHEMBIENCE_BUILD_LABEL}
    depends_on:
      - python
    command: bash

  db:
    image: markussitzmann/chembience_db:${CHEMBIENCE_BUILD_LABEL}
    build:
      context: https://github.com/markussitzmann/docker-postgresql.git#chembience
      args:
        build_label: ${CHEMBIENCE_BUILD_LABEL}
    depends_on:
       - base

  app:
    image: markussitzmann/chembience_app:${CHEMBIENCE_BUILD_LABEL}
    build:
      context: app/
      args:
        build_label: ${CHEMBIENCE_BUILD_LABEL}
    depends_on:
      - django




