#!/bin/bash

./env-prepare

if [ -z $(docker network ls --filter name=^chembience_network$ --format="{{ .Name }}") ] ; then
     echo "Creating chembience sphere network"
     docker network create chembience_network ;
fi

echo "Done."

exit 0
