version: '3'

services:

  base:
    image: chembience/base:${CHEMBIENCE_BUILD_LABEL}
    build:
      context: base/
    volumes:
      - "${CHEMBIENCE_HOME}:/home/chembience"
    environment:
      - CHEMBIENCE_BUILD_LABEL
      - CHEMBIENCE_HOME
      - CHEMBIENCE_USER
      - CHEMBIENCE_UID
      - CHEMBIENCE_GID


  python_base:
    image: chembience/python_base:${CHEMBIENCE_BUILD_LABEL}
    build:
      context: python/
      args:
        build_label: ${CHEMBIENCE_BUILD_LABEL}
    depends_on:
      - base


  rdkit_base:
    image: chembience/rdkit_base:${CHEMBIENCE_BUILD_LABEL}
    build:
      context: rdkit/
      args:
        build_label: ${CHEMBIENCE_BUILD_LABEL}
    depends_on:
      - python_base


  django_base:
    image: chembience/django_base:${CHEMBIENCE_BUILD_LABEL}
    build:
      context: django/
      args:
        build_label: ${CHEMBIENCE_BUILD_LABEL}
    depends_on:
      - rdkit_base






