version: '3'

services:

  base:
    image: chembience/base:${CHEMBIENCE_BUILD_LABEL}
    build:
      context: base/
    environment:
      - CHEMBIENCE_UID
      - CHEMBIENCE_GID


  python_base:
    image: chembience/python_base:${CHEMBIENCE_BUILD_LABEL}
    build:
      context: python/
      args:
        build_label: ${CHEMBIENCE_BUILD_LABEL}
    depends_on:
      - base


  rdkit_base:
    image: chembience/rdkit_base:${CHEMBIENCE_BUILD_LABEL}
    build:
      context: rdkit/
      args:
        build_label: ${CHEMBIENCE_BUILD_LABEL}
    depends_on:
      - python_base
#      - rdkit-conda-compile


  django_base:
    image: chembience/django_base:${CHEMBIENCE_BUILD_LABEL}
    build:
      context: django/
      args:
        build_label: ${CHEMBIENCE_BUILD_LABEL}
    depends_on:
      - rdkit_base


  jupyter_base:
    image: chembience/jupyter_base:${CHEMBIENCE_BUILD_LABEL}
    build:
      context: jupyter/
      args:
        build_label: ${CHEMBIENCE_BUILD_LABEL}
    depends_on:
      - rdkit_base


#  rdkit-conda-compile:
#    image: chembience/rdkit_conda_compile:${CHEMBIENCE_BUILD_LABEL}
#    build:
#      context: rdkit-conda-compile/
#      args:
#        build_label: ${CHEMBIENCE_BUILD_LABEL}


  rdkit-postgres-compile:
    image: chembience/rdkit_postgres_compile:${CHEMBIENCE_BUILD_LABEL}
    build:
      context: rdkit-postgres-compile/
      args:
        build_label: ${CHEMBIENCE_BUILD_LABEL}




