version: '3'

services:

  proxy:
    image: chembience/proxy:${CHEMBIENCE_BUILD_LABEL}
    build:
      context: https://github.com/chembience/nginx-proxy.git#chembience


  shell:
    image: chembience/shell:${CHEMBIENCE_BUILD_LABEL}
    build:
      context: shell/
      args:
        build_label: ${CHEMBIENCE_BUILD_LABEL}
    command: bash


  db:
    image: chembience/db:${CHEMBIENCE_BUILD_LABEL}
    build:
      context: https://github.com/chembience/docker-postgresql.git#chembience
      args:
        build_label: ${CHEMBIENCE_BUILD_LABEL}


  django:
    image: chembience/django:${CHEMBIENCE_BUILD_LABEL}
    build:
      context: django/
      args:
        build_label: ${CHEMBIENCE_BUILD_LABEL}


  rdkit:
    image: chembience/rdkit:${CHEMBIENCE_BUILD_LABEL}
    build:
      context: rdkit/
      args:
        build_label: ${CHEMBIENCE_BUILD_LABEL}


  jupyter:
    image: chembience/jupyter:${CHEMBIENCE_BUILD_LABEL}
    build:
      context: jupyter/
      args:
        build_label: ${CHEMBIENCE_BUILD_LABEL}