version: '3'

services:


  shell:
    image: chembience/shell:${CHEMBIENCE_VERSION}
    build:
      context: shell/
      args:
        build_tag: ${CHEMBIENCE_VERSION}
    command: bash


  django:
    image: chembience/django:${CHEMBIENCE_VERSION}
    build:
      context: django/
      args:
        build_tag: ${CHEMBIENCE_VERSION}
    volumes:
      - "${DJANGO_APP_HOME}:/home/app"


  jupyter:
    image: chembience/jupyter:${CHEMBIENCE_VERSION}
    build:
      context: jupyter/
      args:
        build_tag: ${CHEMBIENCE_VERSION}
    volumes:
      - "${JUPYTER_APP_HOME}:/home/app"


  rdkit:
    image: chembience/rdkit:${CHEMBIENCE_VERSION}
    build:
      context: rdkit/
      args:
        build_tag: ${CHEMBIENCE_VERSION}
    volumes:
      - "${RDKIT_APP_HOME}:/home/app"