version: '3.9'

services:

  app:
    image: ${APP_NAME}:${APP_VERSION}
    container_name: ${APP_NAME}
    volumes:
      - ${APP_HOME}:/home/app
      - ${APP_HOME}/nginx:/home/nginx
      - ${CHEMBIENCE_SHARE}:/share
    ports:
       - ${APP_CONNECTION_PORT}:8888
    networks:
      - app_network
      - chembience_network
    environment:
      - CHEMBIENCE_UID
      - CHEMBIENCE_GID
      - POSTGRES_USER
      - POSTGRES_NAME
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_PASSWORD
      - APP_VIRTUAL_HOSTNAME=${APP_VIRTUAL_HOSTNAME}
      - VIRTUAL_HOST=${APP_VIRTUAL_HOSTNAME}
      - JUPYTER_CONFIG_DIR=/home/app/${JUPYTER_CONFIG_DIR}
      - JUPYTER_NOTEBOOK_DIR=/home/app/${JUPYTER_NOTEBOOK_DIR}
      - JUPYTER_PASSWORD
    depends_on:
      - postgres
    entrypoint: ["/home/app/docker-entrypoint.sh"]
    command: ["/home/nginx/run.sh"]


  postgres:
    image: chembience/postgres-rdkit:${POSTGRES_RDKIT_VERSION}
    container_name: ${APP_NAME}_postgres
    volumes:
      - postgres_db_volume:/var/lib/postgresql
      - ${APP_HOME}/postgres-init.d:/docker-entrypoint-initdb.d
    #restart: always
    networks:
      - app_network
    environment:
      - POSTGRES_USER
      - POSTGRES_NAME
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_PASSWORD

volumes:
  postgres_db_volume:

networks:
  app_network:
    external:
      name: ${APP_NAME}_backend
  chembience_network:
    external:
      name: chembience_network

