version: '3.9'

services:

  app:
    image: chembience/jupyter-rdkit:${CHEMBIENCE_VERSION}
    container_name: ${APP_NAME}
    volumes:
      - ${APP_HOME}:/home/app
      - ${APP_HOME}/nginx:/home/nginx
      - ${CHEMBIENCE_SHARE}:/share
    ports:
       - ${APP_CONNECTION_PORT}:8888
    networks:
      - app-network
    environment:
      - CHEMBIENCE_UID
      - CHEMBIENCE_GID
      - POSTGRES_USER
      - POSTGRES_NAME
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_PASSWORD
      - APP_VIRTUAL_HOSTNAME=${APP_VIRTUAL_HOSTNAME}
      - VIRTUAL_HOST=${APP_VIRTUAL_HOSTNAME}
      - JUPYTER_CONFIG_DIR=/home/app/${JUPYTER_CONFIG_DIR}
      - JUPYTER_NOTEBOOK_DIR=/home/app/${JUPYTER_NOTEBOOK_DIR}
      - JUPYTER_PASSWORD
    depends_on:
      - postgres
    entrypoint: ["/home/app/docker-entrypoint.sh"]
    command: ["/home/nginx/run.sh"]

  postgres:
    image: chembience/postgres-rdkit:${POSTGRES_RDKIT_VERSION}
    container_name: ${APP_NAME}-postgres
    volumes:
      - postgres-db-volume:/var/lib/postgresql
      - ${APP_HOME}/postgres-init.d:/docker-entrypoint-initdb.d
    #restart: always
    networks:
      - app-network
    environment:
      - POSTGRES_USER
      - POSTGRES_NAME
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_PASSWORD

volumes:
  postgres-db-volume:

networks:
  app-network:
    name: ${APP_NAME}-backend


