version: '3.9'

services:

  app:
    image: ${APP_NAME}:${APP_VERSION}
    build:
      context: .
      args:
        build_tag: ${APP_VERSION}
        source_image: ${APP_NAME}

  chembience-image:
    image: ${CHEMBIENCE_IMAGE_NAME}:${CHEMBIENCE_VERSION}


