version: '3'

services:

  shell:
    image: chembience/shell:${CHEMBIENCE_BUILD_LABEL}
    #container_name: chembience_shell
    volumes:
      - "${CHEMBIENCE_SPHERE}:/home/chembience"
    networks:
      - sphere
    environment:
      - CHEMBIENCE_UID
      - CHEMBIENCE_GID
    command: bash
    entrypoint: [""]

networks:
  sphere:



