version: '3'

services:

  jupyter:
    image: chembience/jupyter:${CHEMBIENCE_BUILD_LABEL}
    container_name: chembience_jupyter
    volumes:
      - "${JUPYTER_APP_HOME}:/home/app"
      - "${CHEMBIENCE_HOME}:/home/sphere"
      - "${CHEMBIENCE_SHARE}:/home/share"
    ports:
       - "${JUPYTER_APP_CONNECTION_PORT}:80"
    networks:
      - sphere
    environment:
      - CHEMBIENCE_USER
      - CHEMBIENCE_UID
      - CHEMBIENCE_GID
      - CHEMBIENCE_DB_HOST
      - CHEMBIENCE_DB_PORT
      - CHEMBIENCE_DB_PASSWORD
      - APP_HOME=${JUPYTER_APP_HOME}
      - APP_VIRTUAL_HOSTNAME=${JUPYTER_APP_VIRTUAL_HOSTNAME}
      - VIRTUAL_HOST=${JUPYTER_APP_VIRTUAL_HOSTNAME}
      - JUPYTER_CONFIG_DIR=/home/app
    depends_on:
      - proxy
      - db
    entrypoint: ["/home/app/docker-entrypoint.sh"]
    command: ["/home/nginx/run.sh"]

  proxy:
    image: chembience/proxy:${CHEMBIENCE_BUILD_LABEL}
    container_name: chembience_proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "${CHEMBIENCE_HOME}:/home/chembience"
    ports:
      - "${PROXY_EXTERNAL_PORT}:80"
    networks:
      - sphere

  db:
    image: chembience/db:${CHEMBIENCE_BUILD_LABEL}
    container_name: chembience_db
    volumes:
      - db_volume:/var/lib/postgresql
    networks:
      - sphere
    environment:
      - DEBUG=false
      - CHEMBIENCE_BUILD_LABEL
      - CHEMBIENCE_ROOT
      - CHEMBIENCE_HOME
      - CHEMBIENCE_USER
      - CHEMBIENCE_UID
      - CHEMBIENCE_GID
      - DB_USER=${CHEMBIENCE_USER}
      - DB_PASS=${CHEMBIENCE_DB_PASSWORD}
      - DB_NAME=${CHEMBIENCE_USER}
      - DB_TEMPLATE=
      - DB_EXTENSION=rdkit
      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=

volumes:
  db_volume:

networks:
  sphere:
