name: Chembience build and publish

on:
  push:
    branches:
      - ci
      - develop*
      - image
    tags:
      - v*
  pull_request:


jobs:

  build-and-publish:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}

      - name: base build and push
        run: |
          ./env-prepare
          docker-compose -f ./context/build/docker-compose.build.yml build base
          docker-compose -f ./context/build/docker-compose.build.yml push base

      - name: RDKit Template App build
        run: |
          docker-compose -f ./context/build/docker-compose.build.yml build rdkit

      - name: RDKit Template App push
        run: |
          docker-compose -f ./context/build/docker-compose.build.yml push rdkit

      - name: Django Template App build
        run: |
          docker-compose -f ./context/build/docker-compose.build.yml build django

      - name: Django Template App push
        run: |
          docker-compose -f ./context/build/docker-compose.build.yml push django

      - name: Jupyter Template App build
        run: |
          docker-compose -f ./context/build/docker-compose.build.yml build jupyter

      - name: Jupyter Template App push
        run: |
          docker-compose -f ./context/build/docker-compose.build.yml push jupyter






