name: Docker

on:
  push:
    branches:
      #- master
      - ci
    tags:
      - v*

  pull_request:


jobs:

  build-and-publish:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: "markussitzmann"
          password: ${{ secrets.DOCKER_PASSWD }}

      - name: base build and push
        run: |
          ./env-prepare
          docker-compose -f ./context/build/docker-compose.build.yml build base python-base rdkit-base
          docker-compose -f ./context/app/docker-compose.build.yml build shell
          docker-compose -f ./context/build/docker-compose.build.yml push base python-base rdkit-base
          docker-compose -f ./context/app/docker-compose.build.yml push shell

      - name: Django Template App build
        run: |
          docker-compose -f ./context/build/docker-compose.build.yml build django-base
          docker-compose -f ./context/app/docker-compose.build.yml build django

      - name: Django Template App test
        run: |
          ./init django
          cd ~/chembient/django
          ./up
          ./django-manage-py migrate
          ./django-manage-py createsuperuser --username test --noinput --email test@test.org
          ./django-manage-py collectstatic
          ./remove

      - name: Django Template App push
        run: |
          docker-compose -f ./context/build/docker-compose.build.yml push django-base
          docker-compose -f ./context/app/docker-compose.build.yml push django

      - name: Jupyter Template App build
        run: |
          docker-compose -f ./context/build/docker-compose.build.yml build jupyter-base
          docker-compose -f ./context/app/docker-compose.build.yml build jupyter

      - name: Jupyter Template App test
        run: |
          ./init jupyter
          cd ~/chembient/jupyter
          ./up
          ./jupyter --version
          ./remove

      - name: Jupyter Template App push
        run: |
          docker-compose -f ./context/build/docker-compose.build.yml push jupyter-base
          docker-compose -f ./context/app/docker-compose.build.yml push jupyter

      - name: RDKit Template App build
        run: |
          docker-compose -f ./context/app/docker-compose.build.yml build rdkit

      - name: RDKit Template App test
        run: |
          ./init
          cd ~/chembient/rdkit
          ./run script.py
          ./remove

      - name: RDKit Template App push
        run: |
          docker-compose -f ./context/app/docker-compose.build.yml push rdkit





