name: Docker

on:
  push:
    branches:
      #- master
      - ci
    tags:
      - v*

  pull_request:


jobs:

  build-and-publish:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: "markussitzmann"
          password: ${{ secrets.DOCKER_PASSWD }}

      - name: prepare
        run: |
          ./env-prepare
          docker-compose -f ./context/build/docker-compose.build.yml build base python-base rdkit-base
          docker-compose -f ./context/app/docker-compose.build.yml build shell
          docker-compose -f ./context/build/docker-compose.build.yml push base python-base rdkit-base
          docker-compose -f ./context/app/docker-compose.build.yml push shell

      - name: Django Template App
        run: |
          docker-compose -f ./context/build/docker-compose.build.yml build django-base
          docker-compose -f ./context/app/docker-compose.build.yml build django
          docker-compose -f ./context/app/docker-compose.build.yml push django-base django

      - name: Jupyter Template App
        run: |
          docker-compose -f ./context/build/docker-compose.build.yml build jupyter-base
          docker-compose -f ./context/app/docker-compose.build.yml build jupyter
          docker-compose -f ./context/app/docker-compose.build.yml push jupyter-base jupyter

      - name: RDKit Template App
        run: |
          docker-compose -f ./context/app/docker-compose.build.yml build rdkit
          docker-compose -f ./context/app/docker-compose.build.yml push rdkit

