name: Docker

on:
  push:
    branches:
      #- master
      - ci
    tags:
      - v*

  pull_request:


jobs:

  push:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: "markussitzmann"
          password: ${{ secrets.DOCKER_PASSWD }}

      - name: Build Django Template App
        run: |
          ./build django

      - name: Push Django Image
        run: |
           docker-compose -f ./context/app/docker-compose.build.yml push django

          
