name: Docker

on:
  push:
    branches:
      #- master
      - ci
    tags:
      - v*

  pull_request:


jobs:

  push:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: "markussitzmann"
          password: ${{ secrets.DOCKER_PASSWD }}

      - name: Build RDKit Template App
        run: |
          ./env-prepare
          docker-compose -f ./context/build/docker-compose.build.yml build base python-base rdkit-base
          docker-compose -f ./context/app/docker-compose.build.yml build shell rdkit

      - name: Push RDKit Image
        run: |
          docker-compose -f ./context/build/docker-compose.build.yml push base python-base rdkit-base
          docker-compose -f ./context/app/docker-compose.build.yml push shell rdkit

          
