name: Docker

on:
  push:
    branches:
      - ci-test

  pull_request:


jobs:

  test:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: prepare
        run: |
          ./env-prepare

      - name: Django Template App test
        run: |
          ./init django
          cd ~/chembient/django
          ./up
          ./django-manage-py migrate
          ./django-manage-py createsuperuser --username test --noinput --email test@test.org
          ./django-manage-py collectstatic
          docker-compose logs
          ./remove

      - name: Jupyter Template App test
        run: |
          ./init jupyter
          cd ~/chembient/jupyter
          docker-compose up -d
          ./jupyter --version
          docker-compose log
          docker-compose down

      - name: RDKit Template App test
        run: |
          ./init rdkit
          cd ~/chembient/rdkit
          ./run script.py
          docker-compose log
          docker-compose down







